Use per-station folder locations, changes needed in batchff, batchloop, batchthumbs, makemp4, moviemerge, mp4check, newcasting , castingwatch , drupal-install , mediacopy

diff --git a/bin/batchloop b/bin/batchloop
--- a/bin/batchloop
+++ b/bin/batchloop
@@ -3,24 +3,31 @@
 PGM=$(basename $0)
 TMP=/tmp/$PGM.$$
 
+SDDIR=../mp4
+HDDIR=../mp4-hd
+WEBDIR=../web
+
+[ -f $(dirname "$0")/casting-helpers ] && . $(dirname "$0")/casting-helpers || exit 1
+
 if [ "$1" == "--large" ]
 	then
-	dest=../mp4-hd
+	dest=$HDDIR
 	method=$2
 else
-	dest=../mp4
+	dest=$SDDIR
 	method=$1
 fi
 
 [ ! -d "$dest" ] && echo "$dest missing" && exit 1
-[ ! -d "../web" ] && echo "../web missing" && exit 2
+[ ! -d "$WEBDIR" ] && echo "$WEBDIR missing" && exit 2
+mkdir -p "$WEBDIR/.browsercache"
 
 while true
 do
 	# scratchmove --mp4 ./ $dest/
 	batchff liste
 	batchthumbs liste $method > $TMP.playlist
-	mv $TMP.playlist ../web/playlist.php
+	mv $TMP.playlist $WEBDIR/playlist.php
 
 	# batchturbo liste
 	# batchthumbs liste > playlist.php
