makemp4: 	 - fix temp file name bug 	 - display errors count when exiting

diff --git a/bin/makemp4 b/bin/makemp4
--- a/bin/makemp4
+++ b/bin/makemp4
@@ -97,6 +97,8 @@ echo "$size" | egrep -q "^[0-9]+x[0-9]+$" \
 
 TMP="$destfolder/.$PGM.$$"
 
+errors=0
+
 for file in "$@"
 do
     cd $ORIPWD
@@ -104,14 +106,22 @@ do
     
     command=ffmpeg
     name=$(basename "$file" | sed "s/\.[a-zA-Z0-9]*$//")
+    tmpfile=$TMP.processing.mp4
     command="$command -i $file"
     [ ! $output ] && output=$destfolder/$name.mp4
     [ -f "$output" ] && echo "$PGM: $output exists" && continue
 
     command="$command -acodec libfaac -ab 160000 -s $size -vcodec libx264 -coder 1 -flags +loop -cmp +chroma -partitions +parti8x8+parti4x4+partp8x8+partb8x8 -me_method umh -subq 8 -me_range 16 -g 250 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -b_strategy 2 -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -bf 3 -refs 5 -directpred 3 -trellis 1 -flags2 +bpyramid+mixed_refs+wpred+dct8x8+fastpskip -wpredp 2 -coder 0 -bf 0 -refs 1 -flags2 -wpred-dct8x8 -level 30 -maxrate 10000000 -bufsize 10000000 -wpredp 0 -b $bitrate -threads 0 -f mp4"
-    $command "$TMP.processing.mp4"
-    [ -f $TMP.$name.mp4 ] && mv "$TMP.processing.mp4" "$output"
+    $command "$tmpfile"
+    [ -f $tmpfile ] && mv "$tmpfile" "$output" || {
+	errors=$(($errors + 1))
+	log 1 Could not make $tmpfile
+    }
     unset output
 done
 
-end
+echo "errors $errors"
+[ $errors -eq 1 ] && errors="$errors $errors error" || {
+    [ $errors -gt 1 ] && errors="$errors $errors errors"
+}
+end $errors
