rethumb-comedian added tests, only process if comedian and video found

diff --git a/bin/rethumb-comedian b/bin/rethumb-comedian
--- a/bin/rethumb-comedian
+++ b/bin/rethumb-comedian
@@ -12,13 +12,19 @@ then
   [ "$director" = "bobines" ] && offset=-1 || offset=+1
 fi
 
+[ -f "liste" ] || end $? "List not found, not a casting directory?"
+
 for c in $@
 do
   name=$(grep "[[:blank:]]$c-[^,]*$" liste | sed -E "s/^[0-9,-]+[[:blank:]]+//" | head -1)
+  [ ! "$name" ] && log 1 "Comedian $c not found" && continue
   echo "$name"
   v=$(grep "[[:blank:]]$c-" liste | cut -d " " -f 1 | cut -f 1 | head -1)
+  [ ! "$v" ] && log 1 "No video found for comedian $c $name" && continue
+  [ ! -f "$v.mov" ] && log 1 "Video $v.mov not found" && continue
   # echo $v.mov
   d=$(grep ^$v.mov times | sed -E "s/.*[[:blank:]]([0-9]+)[[:blank:]]/\1/")
+  [ ! "$d" ] && log 1 "Duration not found for video $v.mov" && continue
   if [ -f .$v.thumbtime ]
   then
     t=$(cat .$v.thumbtime)
